spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE #json naming strategy is snake case, auto convert from camel case to snake case.
  datasource: # define how to connect to the database
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql" # database script, pre-written data.
  cache:
    caffeine:
      spec: expireAfterWrite=1m


logging: # Logging incoming http request
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL
